 # Analysis of a grib file using pygrib

pygrib will need to be installed prior to using this notebook.

In order to install pygrib, you can use conda: 

`conda install -c conda-forge pygrib`

In [1]:
import pygrib

<frozen importlib._bootstrap>:219: UserWarning: Warning: ecCodes 2.19.1 or higher is recommended. You are running 2.18.0.


In [2]:
# We'll be using widgets in the notebook
import ipywidgets as widgets 
from IPython.display import display

### Now to select a grib file
This can be any grib file, but you can use our example grib file in the `data/` directory of this repository.

In [3]:
grib_file = '../data/gdas.t12z.pgrb2.1p00.f000'

Opening a Grib file in pygrib is similar to any other file. 

Additionally, since it seeks to different byte offsets in the file, it only loads into memory what you ask.

In [4]:
fh = pygrib.open(grib_file)

In [5]:
num_messages = fh.messages
print(num_messages)

522


In [6]:
fh.message(1)

1:Cloud mixing ratio:kg kg**-1 (instant):regular_ll:hybrid:level 1:fcst time 0 hrs:from 202012111200

Now we can select the variables

In [8]:
grib_messages = [(fh.message(i), i) for i in range(1,num_messages)]

w = widgets.Dropdown(
options=grib_messages,
value=1,
description="Select which grib message you would like to analyze")
display(w)

Dropdown(description='Select which grib message you would like to visualize', options=((1:Cloud mixing ratio:k…

In [43]:
w.value
fh.seek(w.value)
message = fh[w.value]
data = message.values

lats,lons = message.latlons()

### With your variable selected, we can now Analyze the data.

In [16]:
import numpy as np

`data` at this point is a numpy array, which allows for a variety of actions.

In [27]:
data.min()

230.00568359375

In [28]:
data.max()

315.57568359375

In [31]:
np.average(data)


278.1476587318715

In [32]:
# Or, over a region
np.average(data[10:15,20:22])

261.40168359375

In [44]:
# Filter data
max_value = 300
idxs = np.where(data > max_value)
data[idxs] = 0
data

array([[251.67568359, 251.67568359, 251.67568359, ..., 251.67568359,
        251.67568359, 251.67568359],
       [245.79568359, 245.81568359, 245.85568359, ..., 245.77568359,
        245.77568359, 245.78568359],
       [247.21568359, 247.20568359, 247.18568359, ..., 247.31568359,
        247.27568359, 247.23568359],
       ...,
       [252.14568359, 252.14568359, 252.13568359, ..., 252.28568359,
        252.23568359, 252.17568359],
       [250.95568359, 250.93568359, 250.94568359, ..., 250.99568359,
        250.97568359, 250.96568359],
       [249.81568359, 249.81568359, 249.81568359, ..., 249.81568359,
        249.81568359, 249.81568359]])

In [45]:
idxs

(array([ 61,  62,  62, ..., 123, 123, 123]),
 array([ 31,  30,  31, ..., 143, 145, 303]))